extends WallSequence
class_name Sequence1
# Scale, direction, posture
func _init():
	sequence = [
		PostureDTO.new(SIZE.SMALL, DIRECTION.LEFT, POSTURE.NINJA),
		PostureDTO.new(SIZE.MEDIUM, DIRECTION.RIGHT, POSTURE.IDLE),
		PostureDTO.new(SIZE.LARGE, DIRECTION.LEFT, POSTURE.WAVE),
		PostureDTO.new(SIZE.SMALL, DIRECTION.LEFT, POSTURE.BREAK),
		PostureDTO.new(SIZE.LARGE, DIRECTION.RIGHT, POSTURE.KNEEL),
		PostureDTO.new(SIZE.LARGE, DIRECTION.RIGHT, POSTURE.NINJA),
		PostureDTO.new(SIZE.MEDIUM, DIRECTION.LEFT, POSTURE.NINJA),
		PostureDTO.new(SIZE.MEDIUM, DIRECTION.LEFT, POSTURE.NINJA),
		PostureDTO.new(SIZE.SMALL, DIRECTION.LEFT, POSTURE.NINJA),
		PostureDTO.new(SIZE.SMALL, DIRECTION.LEFT, POSTURE.NINJA),
		PostureDTO.new(SIZE.SMALL, DIRECTION.LEFT, POSTURE.NINJA),
	]
