extends WallSequence
class_name Sequence3
# Scale, direction, posture
#8, intro, 11-18
#16 breakdown 1, 19-34
#4 bridge, 35-38
#8 breakdown 2, 39-46
# waves
#1 Funny Final Pose note
func _init():
	sequence = [
		PostureDTO.new(SIZE.MEDIUM, DIRECTION.RIGHT, POSTURE.FIGHT),
		PostureDTO.new(SIZE.MEDIUM, DIRECTION.RIGHT, POSTURE.FIGHT),
		PostureDTO.new(SIZE.MEDIUM, DIRECTION.RIGHT, POSTURE.FIGHT),
		PostureDTO.new(SIZE.MEDIUM, DIRECTION.RIGHT, POSTURE.CROUCH),
		PostureDTO.new(SIZE.MEDIUM, DIRECTION.RIGHT, POSTURE.CROUCH),
		PostureDTO.new(SIZE.MEDIUM, DIRECTION.RIGHT, POSTURE.CROUCH),
		PostureDTO.new(SIZE.MEDIUM, DIRECTION.LEFT, POSTURE.WAVE),
		PostureDTO.new(SIZE.MEDIUM, DIRECTION.LEFT, POSTURE.WAVE),
		PostureDTO.new(SIZE.MEDIUM, DIRECTION.LEFT, POSTURE.WAVE),
		PostureDTO.new(SIZE.MEDIUM, DIRECTION.LEFT, POSTURE.POINT),
		PostureDTO.new(SIZE.MEDIUM, DIRECTION.LEFT, POSTURE.POINT),
		PostureDTO.new(SIZE.MEDIUM, DIRECTION.LEFT, POSTURE.POINT),
		PostureDTO.new(SIZE.SMALL, DIRECTION.RIGHT, POSTURE.FIGHT),
		PostureDTO.new(SIZE.SMALL, DIRECTION.RIGHT, POSTURE.FIGHT),
		PostureDTO.new(SIZE.SMALL, DIRECTION.RIGHT, POSTURE.FIGHT),
		PostureDTO.new(SIZE.SMALL, DIRECTION.RIGHT, POSTURE.CROUCH),
		PostureDTO.new(SIZE.SMALL, DIRECTION.RIGHT, POSTURE.CROUCH),
		PostureDTO.new(SIZE.SMALL, DIRECTION.RIGHT, POSTURE.CROUCH),
		PostureDTO.new(SIZE.SMALL, DIRECTION.LEFT, POSTURE.WAVE),
		PostureDTO.new(SIZE.SMALL, DIRECTION.LEFT, POSTURE.WAVE),
		PostureDTO.new(SIZE.SMALL, DIRECTION.LEFT, POSTURE.WAVE),
		PostureDTO.new(SIZE.SMALL, DIRECTION.LEFT, POSTURE.POINT),
		PostureDTO.new(SIZE.SMALL, DIRECTION.LEFT, POSTURE.POINT),
		PostureDTO.new(SIZE.SMALL, DIRECTION.LEFT, POSTURE.POINT),
		PostureDTO.new(SIZE.LARGE, DIRECTION.RIGHT, POSTURE.FIGHT),
		PostureDTO.new(SIZE.LARGE, DIRECTION.RIGHT, POSTURE.FIGHT),
		PostureDTO.new(SIZE.LARGE, DIRECTION.RIGHT, POSTURE.FIGHT),
		PostureDTO.new(SIZE.LARGE, DIRECTION.RIGHT, POSTURE.CROUCH),
		PostureDTO.new(SIZE.LARGE, DIRECTION.RIGHT, POSTURE.CROUCH),
		PostureDTO.new(SIZE.LARGE, DIRECTION.RIGHT, POSTURE.CROUCH),
		PostureDTO.new(SIZE.LARGE, DIRECTION.LEFT, POSTURE.WAVE),
		PostureDTO.new(SIZE.LARGE, DIRECTION.LEFT, POSTURE.WAVE),
		PostureDTO.new(SIZE.LARGE, DIRECTION.LEFT, POSTURE.WAVE),
		PostureDTO.new(SIZE.LARGE, DIRECTION.LEFT, POSTURE.POINT),
		PostureDTO.new(SIZE.LARGE, DIRECTION.LEFT, POSTURE.POINT),
		PostureDTO.new(SIZE.LARGE, DIRECTION.LEFT, POSTURE.POINT),
	]
