extends WallSequence
class_name Sequence1
# Scale, direction, posture
#9, intro, 12-20
#6 chorus loop 1, 21-26
#6 chorus loop 2, 27-32
#17 breakdown, 33-49
#6 chorus loop 3, 50-55
#6 chorus loop 4, 56-61
func _init():
	sequence = [
		PostureDTO.new(SIZE.MEDIUM, DIRECTION.RIGHT, POSTURE.FIGHT),
		PostureDTO.new(SIZE.MEDIUM, DIRECTION.LEFT, POSTURE.FIGHT),
		PostureDTO.new(SIZE.MEDIUM, DIRECTION.LEFT, POSTURE.CROUCH),
		PostureDTO.new(SIZE.MEDIUM, DIRECTION.RIGHT, POSTURE.CROUCH),
		PostureDTO.new(SIZE.LARGE, DIRECTION.RIGHT, POSTURE.CROUCH),
		PostureDTO.new(SIZE.SMALL, DIRECTION.RIGHT, POSTURE.CROUCH),
		PostureDTO.new(SIZE.MEDIUM, DIRECTION.RIGHT, POSTURE.POINT),
		PostureDTO.new(SIZE.SMALL, DIRECTION.RIGHT, POSTURE.POINT),
		PostureDTO.new(SIZE.LARGE, DIRECTION.RIGHT, POSTURE.POINT),
		PostureDTO.new(SIZE.SMALL, DIRECTION.LEFT, POSTURE.FIGHT),
		PostureDTO.new(SIZE.MEDIUM, DIRECTION.LEFT, POSTURE.FIGHT),
		PostureDTO.new(SIZE.LARGE, DIRECTION.LEFT, POSTURE.WAVE),
		PostureDTO.new(SIZE.SMALL, DIRECTION.RIGHT, POSTURE.WAVE),
		PostureDTO.new(SIZE.MEDIUM, DIRECTION.RIGHT, POSTURE.WAVE),
		PostureDTO.new(SIZE.LARGE, DIRECTION.RIGHT, POSTURE.FIGHT),
		PostureDTO.new(SIZE.SMALL, DIRECTION.LEFT, POSTURE.FIGHT),
		PostureDTO.new(SIZE.MEDIUM, DIRECTION.LEFT, POSTURE.FIGHT),
		PostureDTO.new(SIZE.LARGE, DIRECTION.LEFT, POSTURE.WAVE),
		PostureDTO.new(SIZE.SMALL, DIRECTION.RIGHT, POSTURE.WAVE),
		PostureDTO.new(SIZE.MEDIUM, DIRECTION.RIGHT, POSTURE.WAVE),
		PostureDTO.new(SIZE.LARGE, DIRECTION.RIGHT, POSTURE.FIGHT),
		PostureDTO.new(SIZE.SMALL, DIRECTION.LEFT, POSTURE.WAVE),
		PostureDTO.new(SIZE.SMALL, DIRECTION.LEFT, POSTURE.POINT),
		PostureDTO.new(SIZE.SMALL, DIRECTION.LEFT, POSTURE.FIGHT),
		PostureDTO.new(SIZE.SMALL, DIRECTION.LEFT, POSTURE.CROUCH),
		PostureDTO.new(SIZE.MEDIUM, DIRECTION.LEFT, POSTURE.CROUCH),
		PostureDTO.new(SIZE.LARGE, DIRECTION.LEFT, POSTURE.CROUCH),
		PostureDTO.new(SIZE.LARGE, DIRECTION.RIGHT, POSTURE.CROUCH),
		PostureDTO.new(SIZE.MEDIUM, DIRECTION.RIGHT, POSTURE.CROUCH),
		PostureDTO.new(SIZE.MEDIUM, DIRECTION.RIGHT, POSTURE.CROUCH),
		PostureDTO.new(SIZE.LARGE, DIRECTION.RIGHT, POSTURE.CROUCH),
		PostureDTO.new(SIZE.LARGE, DIRECTION.LEFT, POSTURE.CROUCH),
		PostureDTO.new(SIZE.MEDIUM, DIRECTION.LEFT, POSTURE.CROUCH),
		PostureDTO.new(SIZE.SMALL, DIRECTION.LEFT, POSTURE.FIGHT),
		PostureDTO.new(SIZE.SMALL, DIRECTION.LEFT, POSTURE.POINT),
		PostureDTO.new(SIZE.SMALL, DIRECTION.LEFT, POSTURE.WAVE),
		PostureDTO.new(SIZE.SMALL, DIRECTION.LEFT, POSTURE.CROUCH),
		PostureDTO.new(SIZE.SMALL, DIRECTION.RIGHT, POSTURE.FIGHT),
		PostureDTO.new(SIZE.SMALL, DIRECTION.LEFT, POSTURE.WAVE),
		PostureDTO.new(SIZE.MEDIUM, DIRECTION.LEFT, POSTURE.FIGHT),
		PostureDTO.new(SIZE.LARGE, DIRECTION.LEFT, POSTURE.WAVE),
		PostureDTO.new(SIZE.SMALL, DIRECTION.RIGHT, POSTURE.WAVE),
		PostureDTO.new(SIZE.MEDIUM, DIRECTION.RIGHT, POSTURE.WAVE),
		PostureDTO.new(SIZE.LARGE, DIRECTION.RIGHT, POSTURE.FIGHT),
		PostureDTO.new(SIZE.SMALL, DIRECTION.LEFT, POSTURE.FIGHT),
		PostureDTO.new(SIZE.MEDIUM, DIRECTION.LEFT, POSTURE.FIGHT),
		PostureDTO.new(SIZE.LARGE, DIRECTION.LEFT, POSTURE.WAVE),
		PostureDTO.new(SIZE.SMALL, DIRECTION.RIGHT, POSTURE.WAVE),
		PostureDTO.new(SIZE.MEDIUM, DIRECTION.RIGHT, POSTURE.WAVE),
		PostureDTO.new(SIZE.LARGE, DIRECTION.RIGHT, POSTURE.FIGHT),
	]
