extends WallSequence
class_name Sequence1
# Scale, direction, posture
func _init():
	sequence = [
		PostureDTO.new(SIZE.SMALL, DIRECTION.LEFT, POSTURE.FIGHT),
		PostureDTO.new(SIZE.MEDIUM, DIRECTION.LEFT, POSTURE.CROUCH),
		PostureDTO.new(SIZE.LARGE, DIRECTION.LEFT, POSTURE.FIGHT),
		PostureDTO.new(SIZE.MEDIUM, DIRECTION.LEFT, POSTURE.CROUCH),
		PostureDTO.new(SIZE.LARGE, DIRECTION.RIGHT, POSTURE.FIGHT),
		PostureDTO.new(SIZE.MEDIUM, DIRECTION.LEFT, POSTURE.CROUCH),
		PostureDTO.new(SIZE.SMALL, DIRECTION.LEFT, POSTURE.FIGHT),
		PostureDTO.new(SIZE.SMALL, DIRECTION.LEFT, POSTURE.CROUCH),
		PostureDTO.new(SIZE.SMALL, DIRECTION.LEFT, POSTURE.FIGHT),
		PostureDTO.new(SIZE.SMALL, DIRECTION.LEFT, POSTURE.CROUCH),
		PostureDTO.new(SIZE.SMALL, DIRECTION.LEFT, POSTURE.FIGHT),
		PostureDTO.new(SIZE.SMALL, DIRECTION.LEFT, POSTURE.CROUCH),
		PostureDTO.new(SIZE.SMALL, DIRECTION.LEFT, POSTURE.FIGHT),
		PostureDTO.new(SIZE.SMALL, DIRECTION.LEFT, POSTURE.CROUCH),
		PostureDTO.new(SIZE.SMALL, DIRECTION.LEFT, POSTURE.FIGHT),
		PostureDTO.new(SIZE.SMALL, DIRECTION.LEFT, POSTURE.CROUCH),
		PostureDTO.new(SIZE.SMALL, DIRECTION.LEFT, POSTURE.FIGHT),
		PostureDTO.new(SIZE.SMALL, DIRECTION.LEFT, POSTURE.CROUCH),
		PostureDTO.new(SIZE.SMALL, DIRECTION.LEFT, POSTURE.FIGHT),
	]
